name = "Starlark"
grammar = "starlark"
path_suffixes = [
    "star",
    "bzl",
    "bxl",
    "bazel",
    "bzlmod",
    "WORKSPACE",
    "BUILD",
    "PACKAGE",
    "BUCK",
]
line_comments = ["# "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "b\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "b'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "r\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "r'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "rb\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "rb'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "\"\"\"", end = "\"\"\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "'''", end = "'''", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
    ] },
]

auto_indent_using_last_non_empty_line = false
increase_indent_pattern = ":\\s*$"
decrease_indent_pattern = "^\\s*(else|elif|except|finally)\\b.*:"
