name: Flake Validation

on:
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]

    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                BUILD_TARGET: [release]
        outputs:
            release_built: ${{ steps.set-output.outputs.release_built }}
        steps:
            - uses: actions/checkout@v4
            - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
              run: cargo build --profile ${{ matrix.BUILD_TARGET }}
            - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
              run: cargo test --profile ${{ matrix.BUILD_TARGET }}
